# Generated by Django 3.1.14 on 2025-01-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_auto_20250120_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_to',
        ),
    ]
